### ISSUE TITLE
La paginazione nei controller richiede OrderBy

### ISSUE THREAD

**Issue by AlessandroDelSole** [DuoMes/duo#43]
Nei controller, i metodi Get e SearchByCode eseguono paginazione ma a runtime avviene eccezione secondo cui LINQ to Entities non supporta Skip direttamente e deve essere preceduto da OrderBy

**Comment by nazarenomanco** [comment]
Me ne sono accorto. In sistemazione nell'ultima branch. 

Se vuoi collegati alla mia branch per la gestione delle anagrafiche trattamenti (al momento funziona solo la select)
