### ISSUE TITLE
Aggiunta proprietà Version sulle View

### ISSUE THREAD

**Issue by mauroservienti** [DuoMes/duo#46]
Quando creiamo delle viste, ad esempio `TrattamentoView` o `BobinaMadreView` è importante che queste viste abbiano anche una proprietà `Version` (int) che è presente su tutti gli aggregati. La proprietà `Version` deve poi essere rimandata insieme al comando e serve al `ICommandHandler<MyCommand>` per decidere cosa fare se nel frattempo l'aggregato è cambiato. Quello che vuoi poter fare è una cosa del tipo:

```
public object Handle( ComandoCheFaQualcosaDiInteressante command )
{
   using( var session = Factory.OpenSession() )
   {
      var aggregate = session.GetById<AggregatoFigo>( command.Id );
      if( aggregate.Version != command.Version )
      {
         //che si fa?
      }
   }
}
```

**Comment by nazarenomanco** [comment]
Non si può farlo a livello di Radical.CQRS in maniera infrastrutturale?

**Comment by mauroservienti** [comment]
No, un macello, il toolkit non ha nessun controllo su come tu gestisci le viste e sarebbe troppo complesso farlo lasciandoti la libertà di gestire le viste comunque come vuoi

**Comment by nazarenomanco** [comment]
In effetti per le tabelle "flat" come ora avrebbe un senso... ma la View in CQRS è altro. 
Mi devo staccare dal "vecchio mondo" :smile: 
Eseguo!
