### ISSUE TITLE
Il metodo CambiaCodice in Trattamento non è corretto

### ISSUE THREAD

**Issue by mauroservienti** [DuoMes/duo#47]
Il metodo [CambiaCodice in Trattamento](https://github.com/DuoMes/duo/blob/develop/src/Duo.Domain/Trattamenti/Trattamento.cs#L43) non è corretto, la seguente implementazione:

```
public void CambiaCodice(string codice)
{
    this.RaiseEvent<ITrattamentoCreato>(e =>
    {
        e.Codice = this.Data.Codice;
        e.Descrizione = this.Data.Descrizione;
    });
}
```

contiene due errori:
1. L'evento sollevato è sbagliato, dovrebbe essere `ICodiceTrattamentoModificato`
   - L'evento dovrebbe contenere il vecchio codice e il nuovo codice
2. Manca il salvataggio del nuovo evento

Dovrebbe quindi essere una cosa del tipo:

```
public void CambiaCodice(string codice)
{
    if( this.Data.Codice != codice )
    {
        var vecchio = this.Data.Codice;
        this.Data.Codice = codice;
        this.RaiseEvent<ICodiceTrattamentoModificato>(e =>
        {
            e.NuovoCodice = this.Data.Codice;
            e.VecchioCodice = vecchio;
        });
    }
}
```

**Comment by nazarenomanco** [comment]
Confermo. Lavoro sospeso a metà perché mi ero "perso" tra command e query.Stasera sistemo.

**Comment by mauroservienti** [comment]
Senza fretta, Mea culpa in realtà, perché è [sfuggito a me](https://github.com/DuoMes/duo/pull/37/files#diff-9154361c05180f75f2169b4b47544a95R43).
