### ISSUE TITLE
Cancellazione di una entità

### ISSUE THREAD

**Issue by nazarenomanco** [DuoMes/duo#49]
@mauroservienti, concordo che cancellare "non è bene" in ottica CQRS.

A questo punto è il dev che si implementa la "sua logica di cancellazione" o visto che Radical.CQRS vincola (correttamente) all'Add ma non prevede il delete facciamo in modo (se possibile) di implementarlo sull'Aggregate base di Radical.CQRS?

**Comment by mauroservienti** [comment]
Quello che possiamo fare in `Radical.CQRS` è implementare di default il supporto per la cancellazione logica, il che significa un metodo `MarkAsDeleted` sull'aggregato di base che fa due cose:
- imposta a true la proprietà `IsDeleted`
- Scatena un evento `IAggregateMarkedAsDeleted`

Possiamo poi aggiungere, sempre in `Radical.CQRS`, il supporto per l'eliminazione fisica attraverso ad esempio un `IRepository.Delete( ... )` che permetta di decidere cosa eliminare.

Se devo implementare qualche comportamento di default l'unica cosa che mi piace è la cancellazione fisica, quindi `IRepository.Delete( ... )`, che però introduce una quantità industriale di magagne di design che non vorrei avere. La cancellazione logica è molto ma molto più semplice e è talmente banale da implementare che non ha molto senso che la faccia il toolkit.

**Comment by nazarenomanco** [comment]
Concordo sul fatto che sia banale... ma poichè ritengo che possa servire in quasi tutti gli aggregati secondo me potrebbere esere comodo implementare MarkAsDeleted e IsDeleted direttamente sull'aggregate, magari attraverso l'implementazione dei un'interfaccia ICanBeDeleted?
Una cavolata?

**Comment by mauroservienti** [comment]
> Concordo sul fatto che sia banale... 

Questo fatto che voi dev siate alla ricerca di scorciatoie per scrivere meno codice è un controsenso :smile_cat:  

> ma poiché ritengo che possa servire in quasi tutti gli aggregati secondo me potrebbe essere comodo implementare MarkAsDeleted e IsDeleted direttamente sull'aggregate, magari attraverso l'implementazione dei un'interfaccia ICanBeDeleted?

L'inghippo è che non è banale farlo lato toolkit, se implementi un'interfaccia te lo devi scrivere tu a meno che il codice non sia già nella classe base e viene abilitato dall'interfaccia, ma perché questo avvengo senza interventi il codice deve essere pubblico, il che comporta che potrebbe essere usato a prescindere dall'interfaccia. Ergo ha senso che lo scriva il dev.

Inoltre gli eventi che il toolkit può sollevare sarebbero generici, del tipo `IAggregateDeleted`, e non ha senso architetturalmente.

La cancellazione fisica è paradossalmente più semplice da implementare lato toolkit, ma comporta sempre la rogna degli eventi (e qui una mezza idea ce l'ho), resta il dettaglio che avresti un evento orfano e tutta la storia persa, cosa che sinceramente mi fa orrore :smile:

**Comment by nazarenomanco** [comment]
Sei tu il mago dei toolkit :wink:
Scriverò più codice :smile:
