### ISSUE TITLE
Costruttori / Factory su messaggi

### ISSUE THREAD

**Issue by nazarenomanco** [DuoMes/duo#51]
@mauroservienti, chiedo la best practice come regola generale.
Al momento il dev è libero su Duo di "riempire" i messaggi come più gli aggrada. 

Per abitudine io definisco sempre una Factory per fare in modo che ho il controllo di come è creato e se cambio inizializzazione becco al volo tutti i punti da sistemare. 

Essendo classi molto piccole e senza logica forse va bene anche solo definire un costruttore parametrico, ma almeno questo lo farei. 

La tua impressione?

**Comment by mauroservienti** [comment]
Ha senso. Quello che ti serve però è la possibilità di avere anche un costruttore che viene usato per la deserializzazione, quello che vuoi fare è una cosa del tipo:

```
class MyCommand
{
   private MyCommand(){}  //usato solo da json.net
   public MyCommand( /* args */ ){} //usato da chi vuole lanciare il comando
}
```

#53 abilita il supporto per i costruttori privati.

**Comment by nazarenomanco** [comment]
Ottimo! Grazie!
