### ISSUE TITLE
Aggiunta Version sui comandi

### ISSUE THREAD

**Issue by mauroservienti** [DuoMes/duo#54]
Come in #46 anche i comandi, tranne quelli che creano nuove cose, devono portare con se la versione della view che è stata usata per generarli.

Questo ci serve per:
1. recuperi una vista dal server
2. la vista arriva con una versione
3. L'utente guarda i dati e decide di apportare delle modifiche sulla base di quello che vede (la Versione)
4. Invia il comando al server con la Versione della vista che ha usato
5. il server quando cerchi di caricare un aggregato verifica che la versione che stai caricando sia consistente con quella del comando

**Comment by mauroservienti** [comment]
Faccio in modo di abilitarti a fare questo: https://github.com/RadicalFx/Radical.CQRS/issues/12

**Comment by mauroservienti** [comment]
@nazarenomanco La teoria dice che adesso puoi fare derivare i tuoi `command handler` da `AbstractAggregateCommandHandler<TAggregate, TCommand>`, facendo una cosa del genere:

```
class MyCommandHandler : AbstractAggregateCommandHandler<MyAggregate, MyCommand>
{
   public override void Manipulate(MyAggregate aggregate, MyCommand command)
   {
      //fai quello che devi fare con l'aggregato
      aggregate.FaiQualcosa( command.Parametro );
   }
}
```

Non serve salvare, nulla, il comando deve contenere una proprietà `Id` di tipo `Guid` per la chiave, se il comando contiene una proprietà `Version` di tipo `int` quella viene usata per caricare la versione giusta, altrimenti semplicemente per chiave.

**Comment by nazarenomanco** [comment]
Domanda per capire la logica... ma è bene sempre fare riferimento alla version quando si manda un comando?

**Comment by mauroservienti** [comment]
Sarebbe l'ideale, altrimenti rischi che:
1. recuperi una vista dal server
2. la vista arriva con una versione
3. L'utente guarda i dati e decide di apportare delle modifiche sulla base di quello che vede (la Versione)
4. Invia il comando al server **senza** la Versione della vista che ha usato
5. Nel frattempo un altro utente ha modificato lo stesso aggregato

La modifiche apportate da un altro potrebbero non essere compatibili con quello che vuoi fare tu e in questo caso mi aspetterei un'eccezione, ma c'è uno scenario peggiore:
1. il cliente è insolvente
2. Il comando è `InviaSollecito`
3. Nel frattempo un collega ha marcato il pagamento come avvenuto
4. Se `InviaSollecito` porta con se la versione della verità è facile rimbalzare il comando e dirti senti un po' visto che le informazioni nel frattempo sono cambiate, dai di nuovo un occhio
