### ISSUE TITLE
Eventi su modifica aggregati

### ISSUE THREAD

**Issue by nazarenomanco** [DuoMes/duo#56]
@mauroservienti sai che sono un programmatore pigro :smile: 

Prendiamo ad esempio i trattamenti. L'utente apre la maschera in modifica e potrebbe cambiare codice, descrizione o tutti e due. 
C'è un modo "standard" per capire quali command lanciare e quindi che eventi scatenare?

E' vero che i command hanno la verifica se qualcosa è cambiato per quella proprietà... ma dovrei chiamarli tutti... 

Spero di essere stato chiaro. Grazie!

**Comment by mauroservienti** [comment]
Tutto chiarissimo, diciamo che questo è uno dei limiti ma anche dei vantaggi di CQRS e DDD in genere, la domanda che ha senso farsi è se modifico il codice, ad esempio, ha un significato di business diverso da se modifico la descrizione? Se si allora devono essere comandi, ed eventi, diversi, altrimenti puoi tranquillamente piazzare tutto in uno schifosissimo dictionary e lanciare un comando generico e un altrettanto generico evento. Diciamo che se fosse così sempre forse CQRS è l'approccio sbagliato per il progetto corrente. Avrebbe probabilmente senso valutare se per alcune parti di duo abbia senso fare della banale CRUD.

**Comment by nazarenomanco** [comment]
Direi che questa cosa è meglio smarcarla a voce in 10 minuti che scrivere qui. 
Che ne dici? :smile:

**Comment by nazarenomanco** [comment]
La riapro per scrivere due righe per "fermare" quanto detto a voce. 
Sulle anagrafiche spesso non è interessante tenere traccia di tutte le modifiche per cui si può pensare ad un evento di dominio più generico (IAnagraficaXxxxModificata, ad esempio). 
Quando arriveremo agli aggregati di dominio interessanti vedremo se gestire la logica nell'aggregato o a livello "infrastrutturale".
