### ISSUE TITLE
Gestione Aggregate di anagrafica codice/descrizione

### ISSUE THREAD

**Issue by nazarenomanco** [DuoMes/duo#61]
Ciao, 

 mi sto trovando a creare molti aggregati che hanno Id, Versione, Codice, Descrizione. 
 E' corretta l'idea di definirmi una:

`public abstract class CodeDescriptionAggregate<TState> : Aggregate<TState>`

e se mi è necessario da qualche parte aggiungo le proprietà "in più"?

**Comment by mauroservienti** [comment]
Domanda: per uno stakeholder un `CodeDescriptionAggregate` ha un significato di business?

**Comment by nazarenomanco** [comment]
Lo stakeholder non lo vede... è solo per scrivere meno codice palloso :)

**Comment by mauroservienti** [comment]
Allora ti sei risposto da solo :smile: fai copia e incolla che è meglio. Usare ereditarietà in maniera distorta per scrivere meno codice...no...grazie no :joy:
